/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class DashBoard extends javax.swing.JFrame {

    public Empresa Star;
    public Empresa Nick; 
    int NickGuiones; 
    int NickEscenarios; 
    int NickAnimaciones;
    int NickDoblajes;
    int NickPT;
    int NickEnsambladores; 
    int StarGuiones; 
    int StarEscenarios; 
    int StarAnimaciones;
    int StarDoblajes;
    int StarPT;
    int StarEnsambladores;
    long costosStarValue;
    long costosNickValue;
    boolean click = true;
    
    public DashBoard() {
        
        
        this.setResizable(false);
        initComponents();
        
        
        
        this.guionPanel.setName("guiones");
        this.nivelesPanel.setName("escenarios");
        this.spritesPanel.setName("animaciones");
        this.logicPanel.setName("doblajes");
        this.DLCPanel.setName("PT");
        this.integPanel.setName("ensambladores");
        
        
        this.NickGuiones = (Integer)guionesNick.getValue();
        this.NickEscenarios = (Integer)escenariosNick.getValue();
        this.NickAnimaciones = (Integer)animacionesNick.getValue();
        this.NickDoblajes = (Integer)doblajeNick.getValue();
        this.NickPT = (Integer)PtNick.getValue();
        this.NickEnsambladores = (Integer)ensambladorNick.getValue();
        
        this.StarGuiones = (Integer)guionesStar.getValue();
        this.StarEscenarios = (Integer)escenariosStar.getValue();
        this.StarAnimaciones = (Integer)animacionesStar.getValue();
        this.StarDoblajes = (Integer)logicCA.getValue();
        this.StarPT = (Integer)PtStar.getValue();
        this.StarEnsambladores = (Integer)ensambladorStar.getValue();
        
        this.costosNickValue = 0;
        this.costosNickValue = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devsPanel = new javax.swing.JPanel();
        devCA = new javax.swing.JLabel();
        devNI = new javax.swing.JLabel();
        logicPanel = new javax.swing.JPanel();
        Doblajes = new javax.swing.JLabel();
        doblajeNick = new javax.swing.JSpinner();
        logicCA = new javax.swing.JSpinner();
        DLCPanel = new javax.swing.JPanel();
        PT = new javax.swing.JLabel();
        PtNick = new javax.swing.JSpinner();
        PtStar = new javax.swing.JSpinner();
        devsQtyPanel = new javax.swing.JPanel();
        workerQtyStar = new javax.swing.JLabel();
        devQty = new javax.swing.JLabel();
        workerQtyNick = new javax.swing.JLabel();
        integPanel = new javax.swing.JPanel();
        ensambladores = new javax.swing.JLabel();
        ensambladorNick = new javax.swing.JSpinner();
        ensambladorStar = new javax.swing.JSpinner();
        spritesPanel = new javax.swing.JPanel();
        animadores = new javax.swing.JLabel();
        animacionesNick = new javax.swing.JSpinner();
        animacionesStar = new javax.swing.JSpinner();
        guionPanel = new javax.swing.JPanel();
        guiones = new javax.swing.JLabel();
        guionesNick = new javax.swing.JSpinner();
        guionesStar = new javax.swing.JSpinner();
        nivelesPanel = new javax.swing.JPanel();
        escenario = new javax.swing.JLabel();
        escenariosNick = new javax.swing.JSpinner();
        escenariosStar = new javax.swing.JSpinner();
        disponibilidadPanel = new javax.swing.JPanel();
        tituloDispon = new javax.swing.JLabel();
        disponCA = new javax.swing.JLabel();
        disponNI = new javax.swing.JLabel();
        DLCPanDispon = new javax.swing.JPanel();
        PTDispon = new javax.swing.JLabel();
        PTDisponNick = new javax.swing.JLabel();
        PTDisponStar = new javax.swing.JLabel();
        nivelesPanelDispon = new javax.swing.JPanel();
        escenariosDispon = new javax.swing.JLabel();
        escenariosDisponNick = new javax.swing.JLabel();
        escenariosDisponStar = new javax.swing.JLabel();
        logicPanelDispon = new javax.swing.JPanel();
        doblajesDispon = new javax.swing.JLabel();
        doblajesDisponNick = new javax.swing.JLabel();
        doblajesDisponStar = new javax.swing.JLabel();
        narrativaPanelDispon = new javax.swing.JPanel();
        guionesDispon = new javax.swing.JLabel();
        guionesDisponNick = new javax.swing.JLabel();
        guionesDisponStar = new javax.swing.JLabel();
        spritesPanelDispon = new javax.swing.JPanel();
        animadoresDispon = new javax.swing.JLabel();
        animacionesDisponNick = new javax.swing.JLabel();
        animacionesDisponStar = new javax.swing.JLabel();
        maxCapacidad = new javax.swing.JPanel();
        capMax = new javax.swing.JLabel();
        guionesMax = new javax.swing.JLabel();
        escenariosMax = new javax.swing.JLabel();
        animacionesMax = new javax.swing.JLabel();
        doblajesMax = new javax.swing.JLabel();
        PTMax = new javax.swing.JLabel();
        spritesMaxN = new javax.swing.JLabel();
        guionesMaxN = new javax.swing.JLabel();
        escenariosMaxN = new javax.swing.JLabel();
        DLCMaxN = new javax.swing.JLabel();
        doblajesMaxN = new javax.swing.JLabel();
        listos = new javax.swing.JPanel();
        listosTitle = new javax.swing.JLabel();
        listosTitleCA = new javax.swing.JLabel();
        listosTitleNI = new javax.swing.JLabel();
        conPT = new javax.swing.JLabel();
        qtyListosPTNick = new javax.swing.JLabel();
        qtyListosPTStar = new javax.swing.JLabel();
        Est = new javax.swing.JLabel();
        qtyListosEstNick = new javax.swing.JLabel();
        qtyListosEstStar = new javax.swing.JLabel();
        deadlinePanel = new javax.swing.JPanel();
        deadline = new javax.swing.JLabel();
        deadlineN = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        econPanel = new javax.swing.JPanel();
        listosTitle1 = new javax.swing.JLabel();
        econCapCom = new javax.swing.JLabel();
        econNintendo = new javax.swing.JLabel();
        ingresoNick = new javax.swing.JLabel();
        costosNick = new javax.swing.JLabel();
        profitNick = new javax.swing.JLabel();
        ingresoStar = new javax.swing.JLabel();
        costosStar = new javax.swing.JLabel();
        profitStar = new javax.swing.JLabel();
        costosTitle = new javax.swing.JLabel();
        ingresos = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        PMyDirector = new javax.swing.JPanel();
        estadoDirectorNick = new javax.swing.JLabel();
        estadoPMNick = new javax.swing.JLabel();
        estadoPMStar = new javax.swing.JLabel();
        estadoDirectorStar = new javax.swing.JLabel();
        CapComPMYDirector = new javax.swing.JLabel();
        NintendoPMYDirector = new javax.swing.JLabel();
        directorTitulo = new javax.swing.JLabel();
        PMTitulo = new javax.swing.JLabel();
        faltasTitulo = new javax.swing.JLabel();
        sueldoDescontadoStar = new javax.swing.JLabel();
        qtyFaltasStar = new javax.swing.JLabel();
        qtyFaltasNick = new javax.swing.JLabel();
        sueldoDescontadoNick = new javax.swing.JLabel();
        qtyFaltasTitulo = new javax.swing.JLabel();
        DirectorPMTitulo = new javax.swing.JLabel();
        sueldoDescontadoTitulo = new javax.swing.JLabel();
        inicioBtn = new javax.swing.JButton();
        subirDatos = new javax.swing.JButton();
        duracionTitle = new javax.swing.JLabel();
        duracionValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tituloDevs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devsPanel.setOpaque(false);
        devsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devCA.setForeground(new java.awt.Color(255, 51, 0));
        devCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devCA.setText("Star");
        devsPanel.add(devCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 20, 60, 20));

        devNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devNI.setForeground(new java.awt.Color(255, 153, 0));
        devNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devNI.setText("Nick");
        devsPanel.add(devNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 20));

        logicPanel.setOpaque(false);
        logicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doblajes.setForeground(new java.awt.Color(0, 255, 51));
        Doblajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Doblajes.setText("Doblajes");
        logicPanel.add(Doblajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        doblajeNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        doblajeNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        doblajeNick.setToolTipText("");
        doblajeNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                doblajeNickStateChanged(evt);
            }
        });
        logicPanel.add(doblajeNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        logicCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        logicCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        logicCA.setToolTipText("");
        logicCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logicCAStateChanged(evt);
            }
        });
        logicPanel.add(logicCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(logicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        DLCPanel.setOpaque(false);
        DLCPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PT.setForeground(new java.awt.Color(0, 255, 51));
        PT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PT.setText("PT");
        DLCPanel.add(PT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        PtNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PtNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        PtNick.setToolTipText("");
        PtNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PtNickStateChanged(evt);
            }
        });
        DLCPanel.add(PtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        PtStar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PtStar.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        PtStar.setToolTipText("");
        PtStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PtStarStateChanged(evt);
            }
        });
        DLCPanel.add(PtStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(DLCPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        devsQtyPanel.setOpaque(false);
        devsQtyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workerQtyStar.setForeground(new java.awt.Color(255, 255, 255));
        workerQtyStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workerQtyStar.setText("12");
        devsQtyPanel.add(workerQtyStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        devQty.setForeground(new java.awt.Color(0, 255, 51));
        devQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQty.setText("Trabajadores");
        devsQtyPanel.add(devQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 20));

        workerQtyNick.setForeground(new java.awt.Color(255, 255, 255));
        workerQtyNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workerQtyNick.setText("12");
        devsQtyPanel.add(workerQtyNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        devsPanel.add(devsQtyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        integPanel.setOpaque(false);
        integPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ensambladores.setForeground(new java.awt.Color(0, 255, 51));
        ensambladores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ensambladores.setText("Ensambladores");
        integPanel.add(ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        ensambladorNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ensambladorNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        ensambladorNick.setToolTipText("");
        ensambladorNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ensambladorNickStateChanged(evt);
            }
        });
        integPanel.add(ensambladorNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        ensambladorStar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ensambladorStar.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        ensambladorStar.setToolTipText("");
        ensambladorStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ensambladorStarStateChanged(evt);
            }
        });
        integPanel.add(ensambladorStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(integPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        spritesPanel.setOpaque(false);
        spritesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        animadores.setForeground(new java.awt.Color(0, 255, 51));
        animadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        animadores.setText("Animadores");
        spritesPanel.add(animadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        animacionesNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        animacionesNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        animacionesNick.setToolTipText("");
        animacionesNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                animacionesNickStateChanged(evt);
            }
        });
        spritesPanel.add(animacionesNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        animacionesStar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        animacionesStar.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        animacionesStar.setToolTipText("");
        animacionesStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                animacionesStarStateChanged(evt);
            }
        });
        spritesPanel.add(animacionesStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(spritesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        guionPanel.setOpaque(false);
        guionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiones.setForeground(new java.awt.Color(0, 255, 51));
        guiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guiones.setText("Guiones");
        guionPanel.add(guiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 20));

        guionesNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        guionesNick.setToolTipText("");
        guionesNick.setRequestFocusEnabled(false);
        guionesNick.setValue(2);
        guionesNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesNickStateChanged(evt);
            }
        });
        guionPanel.add(guionesNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        guionesStar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesStar.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        guionesStar.setToolTipText("");
        guionesStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesStarStateChanged(evt);
            }
        });
        guionPanel.add(guionesStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(guionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        nivelesPanel.setOpaque(false);
        nivelesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escenario.setForeground(new java.awt.Color(0, 255, 51));
        escenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escenario.setText("Escenarios");
        nivelesPanel.add(escenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        escenariosNick.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        escenariosNick.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        escenariosNick.setToolTipText("");
        escenariosNick.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                escenariosNickStateChanged(evt);
            }
        });
        nivelesPanel.add(escenariosNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        escenariosStar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        escenariosStar.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        escenariosStar.setToolTipText("");
        escenariosStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                escenariosStarStateChanged(evt);
            }
        });
        nivelesPanel.add(escenariosStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(nivelesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        getContentPane().add(devsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 250));

        disponibilidadPanel.setOpaque(false);
        disponibilidadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloDispon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDispon.setForeground(new java.awt.Color(0, 255, 102));
        tituloDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDispon.setText("DISPONIBILIDAD");
        disponibilidadPanel.add(tituloDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 20));

        disponCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponCA.setForeground(new java.awt.Color(255, 0, 51));
        disponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponCA.setText("Star");
        disponibilidadPanel.add(disponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 20));

        disponNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponNI.setForeground(new java.awt.Color(255, 153, 0));
        disponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponNI.setText("Nick");
        disponibilidadPanel.add(disponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 20));

        DLCPanDispon.setOpaque(false);
        DLCPanDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTDispon.setForeground(new java.awt.Color(0, 255, 51));
        PTDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PTDispon.setText("PT");
        DLCPanDispon.add(PTDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        PTDisponNick.setForeground(new java.awt.Color(255, 255, 255));
        PTDisponNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PTDisponNick.setText("0");
        DLCPanDispon.add(PTDisponNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        PTDisponStar.setForeground(new java.awt.Color(255, 255, 255));
        PTDisponStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PTDisponStar.setText("0");
        DLCPanDispon.add(PTDisponStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(DLCPanDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        nivelesPanelDispon.setOpaque(false);
        nivelesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escenariosDispon.setForeground(new java.awt.Color(0, 255, 51));
        escenariosDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escenariosDispon.setText("Escenarios");
        nivelesPanelDispon.add(escenariosDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        escenariosDisponNick.setForeground(new java.awt.Color(255, 255, 255));
        escenariosDisponNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escenariosDisponNick.setText("0");
        nivelesPanelDispon.add(escenariosDisponNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        escenariosDisponStar.setForeground(new java.awt.Color(255, 255, 255));
        escenariosDisponStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escenariosDisponStar.setText("0");
        nivelesPanelDispon.add(escenariosDisponStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(nivelesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        logicPanelDispon.setOpaque(false);
        logicPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doblajesDispon.setForeground(new java.awt.Color(0, 255, 51));
        doblajesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doblajesDispon.setText("Doblajes");
        logicPanelDispon.add(doblajesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        doblajesDisponNick.setForeground(new java.awt.Color(255, 255, 255));
        doblajesDisponNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doblajesDisponNick.setText("0");
        logicPanelDispon.add(doblajesDisponNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        doblajesDisponStar.setForeground(new java.awt.Color(255, 255, 255));
        doblajesDisponStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doblajesDisponStar.setText("0");
        logicPanelDispon.add(doblajesDisponStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(logicPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        narrativaPanelDispon.setOpaque(false);
        narrativaPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guionesDispon.setForeground(new java.awt.Color(0, 255, 51));
        guionesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDispon.setText("Guiones");
        narrativaPanelDispon.add(guionesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        guionesDisponNick.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponNick.setText("0");
        narrativaPanelDispon.add(guionesDisponNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        guionesDisponStar.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponStar.setText("0");
        narrativaPanelDispon.add(guionesDisponStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(narrativaPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        spritesPanelDispon.setOpaque(false);
        spritesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        animadoresDispon.setForeground(new java.awt.Color(0, 255, 51));
        animadoresDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        animadoresDispon.setText("Animadores");
        spritesPanelDispon.add(animadoresDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        animacionesDisponNick.setForeground(new java.awt.Color(255, 255, 255));
        animacionesDisponNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        animacionesDisponNick.setText("0");
        spritesPanelDispon.add(animacionesDisponNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        animacionesDisponStar.setForeground(new java.awt.Color(255, 255, 255));
        animacionesDisponStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        animacionesDisponStar.setText("0");
        spritesPanelDispon.add(animacionesDisponStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(spritesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        getContentPane().add(disponibilidadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, 220));

        maxCapacidad.setOpaque(false);
        maxCapacidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        capMax.setForeground(new java.awt.Color(0, 255, 0));
        capMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capMax.setText("CAPACIDAD MÁXIMA");
        maxCapacidad.add(capMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        guionesMax.setForeground(new java.awt.Color(0, 255, 0));
        guionesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guionesMax.setText("Guiones");
        maxCapacidad.add(guionesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        escenariosMax.setForeground(new java.awt.Color(0, 255, 51));
        escenariosMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        escenariosMax.setText("Escenarios");
        maxCapacidad.add(escenariosMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 20));

        animacionesMax.setForeground(new java.awt.Color(0, 255, 0));
        animacionesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        animacionesMax.setText("Animaciones");
        maxCapacidad.add(animacionesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        doblajesMax.setForeground(new java.awt.Color(0, 255, 51));
        doblajesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doblajesMax.setText("Doblajes");
        maxCapacidad.add(doblajesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 20));

        PTMax.setForeground(new java.awt.Color(0, 255, 51));
        PTMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PTMax.setText("PTs");
        maxCapacidad.add(PTMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 20));

        spritesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        spritesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesMaxN.setText("0");
        maxCapacidad.add(spritesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        guionesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        guionesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesMaxN.setText("0");
        maxCapacidad.add(guionesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 30, 20));

        escenariosMaxN.setForeground(new java.awt.Color(255, 255, 255));
        escenariosMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escenariosMaxN.setText("0");
        maxCapacidad.add(escenariosMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 20));

        DLCMaxN.setForeground(new java.awt.Color(255, 255, 255));
        DLCMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCMaxN.setText("0");
        maxCapacidad.add(DLCMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 20));

        doblajesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        doblajesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doblajesMaxN.setText("0");
        maxCapacidad.add(doblajesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, 20));

        getContentPane().add(maxCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 170, 140));

        listos.setOpaque(false);
        listos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listosTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitle.setForeground(new java.awt.Color(0, 255, 51));
        listosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitle.setText("VIDEOJUEGOS LISTOS");
        listos.add(listosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 20));

        listosTitleCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleCA.setForeground(new java.awt.Color(255, 0, 0));
        listosTitleCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleCA.setText("Star");
        listos.add(listosTitleCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 20));

        listosTitleNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleNI.setForeground(new java.awt.Color(255, 153, 0));
        listosTitleNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleNI.setText("Nick");
        listos.add(listosTitleNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 20));

        conPT.setForeground(new java.awt.Color(0, 255, 51));
        conPT.setText("Con PT");
        listos.add(conPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        qtyListosPTNick.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosPTNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosPTNick.setText("0");
        listos.add(qtyListosPTNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, -1));

        qtyListosPTStar.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosPTStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosPTStar.setText("0");
        listos.add(qtyListosPTStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 30, -1));

        Est.setForeground(new java.awt.Color(0, 255, 51));
        Est.setText("Estándar");
        listos.add(Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        qtyListosEstNick.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstNick.setText("0");
        listos.add(qtyListosEstNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        qtyListosEstStar.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstStar.setText("0");
        listos.add(qtyListosEstStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, -1));

        getContentPane().add(listos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        deadlinePanel.setOpaque(false);
        deadlinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deadline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deadline.setForeground(new java.awt.Color(0, 255, 51));
        deadline.setText("Deadline (días)");
        deadlinePanel.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        deadlineN.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        deadlineN.setForeground(new java.awt.Color(0, 255, 51));
        deadlineN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadlineN.setText("30");
        deadlinePanel.add(deadlineN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        getContentPane().add(deadlinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 70));

        title1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 255, 0));
        title1.setText("DashBoard by PaCode");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 50));

        econPanel.setOpaque(false);
        econPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listosTitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitle1.setForeground(new java.awt.Color(0, 255, 0));
        listosTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitle1.setText("ASPECTO ECONÓMICO");
        econPanel.add(listosTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 20));

        econCapCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        econCapCom.setForeground(new java.awt.Color(255, 0, 0));
        econCapCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        econCapCom.setText("Star");
        econPanel.add(econCapCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, 20));

        econNintendo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        econNintendo.setForeground(new java.awt.Color(255, 153, 0));
        econNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        econNintendo.setText("Nick");
        econPanel.add(econNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        ingresoNick.setForeground(new java.awt.Color(255, 255, 255));
        ingresoNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoNick.setText("0");
        econPanel.add(ingresoNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, -1));

        costosNick.setForeground(new java.awt.Color(255, 255, 255));
        costosNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosNick.setText("0");
        econPanel.add(costosNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 110, -1));

        profitNick.setForeground(new java.awt.Color(255, 255, 255));
        profitNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profitNick.setText("0");
        econPanel.add(profitNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        ingresoStar.setForeground(new java.awt.Color(255, 255, 255));
        ingresoStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoStar.setText("0");
        econPanel.add(ingresoStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        costosStar.setForeground(new java.awt.Color(255, 255, 255));
        costosStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosStar.setText("0");
        econPanel.add(costosStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));

        profitStar.setForeground(new java.awt.Color(255, 255, 255));
        profitStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profitStar.setText("0");
        econPanel.add(profitStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, -1));

        costosTitle.setForeground(new java.awt.Color(0, 255, 0));
        costosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosTitle.setText("Costos");
        econPanel.add(costosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, -1));

        ingresos.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ingresos.setForeground(new java.awt.Color(0, 255, 0));
        ingresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresos.setText("Ingresos");
        econPanel.add(ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 270, -1));

        profit.setForeground(new java.awt.Color(0, 255, 0));
        profit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profit.setText("Utilidad");
        econPanel.add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, -1));

        getContentPane().add(econPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 270, 120));

        PMyDirector.setOpaque(false);
        PMyDirector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estadoDirectorNick.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        estadoDirectorNick.setForeground(new java.awt.Color(255, 255, 255));
        estadoDirectorNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoDirectorNick.setText("...");
        PMyDirector.add(estadoDirectorNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        estadoPMNick.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        estadoPMNick.setForeground(new java.awt.Color(255, 255, 255));
        estadoPMNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoPMNick.setText("...");
        PMyDirector.add(estadoPMNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, -1));

        estadoPMStar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        estadoPMStar.setForeground(new java.awt.Color(255, 255, 255));
        estadoPMStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoPMStar.setText("...");
        PMyDirector.add(estadoPMStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 120, -1));

        estadoDirectorStar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        estadoDirectorStar.setForeground(new java.awt.Color(255, 255, 255));
        estadoDirectorStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoDirectorStar.setText("...");
        PMyDirector.add(estadoDirectorStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, -1));

        CapComPMYDirector.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CapComPMYDirector.setForeground(new java.awt.Color(255, 0, 0));
        CapComPMYDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CapComPMYDirector.setText("Star");
        PMyDirector.add(CapComPMYDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 70, 20));

        NintendoPMYDirector.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NintendoPMYDirector.setForeground(new java.awt.Color(255, 153, 0));
        NintendoPMYDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NintendoPMYDirector.setText("Nick");
        PMyDirector.add(NintendoPMYDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        directorTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        directorTitulo.setForeground(new java.awt.Color(0, 255, 0));
        directorTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        directorTitulo.setText("DIRECTOR");
        PMyDirector.add(directorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, -1));

        PMTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PMTitulo.setForeground(new java.awt.Color(0, 255, 0));
        PMTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PMTitulo.setText("PROJECT MANAGER");
        PMyDirector.add(PMTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 350, -1));

        faltasTitulo.setForeground(new java.awt.Color(0, 255, 0));
        faltasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        faltasTitulo.setText("Faltas al PM");
        PMyDirector.add(faltasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 270, -1));

        sueldoDescontadoStar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        sueldoDescontadoStar.setForeground(new java.awt.Color(255, 255, 255));
        sueldoDescontadoStar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sueldoDescontadoStar.setText("...");
        PMyDirector.add(sueldoDescontadoStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 70, -1));

        qtyFaltasStar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        qtyFaltasStar.setForeground(new java.awt.Color(255, 255, 255));
        qtyFaltasStar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyFaltasStar.setText("...");
        PMyDirector.add(qtyFaltasStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 20, -1));

        qtyFaltasNick.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        qtyFaltasNick.setForeground(new java.awt.Color(255, 255, 255));
        qtyFaltasNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyFaltasNick.setText("...");
        PMyDirector.add(qtyFaltasNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 20, -1));

        sueldoDescontadoNick.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        sueldoDescontadoNick.setForeground(new java.awt.Color(255, 255, 255));
        sueldoDescontadoNick.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sueldoDescontadoNick.setText("...");
        PMyDirector.add(sueldoDescontadoNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        qtyFaltasTitulo.setForeground(new java.awt.Color(0, 255, 0));
        qtyFaltasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyFaltasTitulo.setText("Cantidad");
        PMyDirector.add(qtyFaltasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 270, -1));

        DirectorPMTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DirectorPMTitulo.setForeground(new java.awt.Color(0, 255, 0));
        DirectorPMTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DirectorPMTitulo.setText("PM y Director");
        PMyDirector.add(DirectorPMTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, 20));

        sueldoDescontadoTitulo.setForeground(new java.awt.Color(0, 255, 0));
        sueldoDescontadoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sueldoDescontadoTitulo.setText("Sueldo descontado");
        PMyDirector.add(sueldoDescontadoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 270, -1));

        getContentPane().add(PMyDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 380, 150));

        inicioBtn.setBackground(new java.awt.Color(0, 255, 0));
        inicioBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        inicioBtn.setText("INICIAR");
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(inicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 40));

        subirDatos.setBackground(new java.awt.Color(0, 255, 51));
        subirDatos.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        subirDatos.setText("Subir Datos");
        subirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirDatosActionPerformed(evt);
            }
        });
        getContentPane().add(subirDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        duracionTitle.setForeground(new java.awt.Color(0, 255, 51));
        duracionTitle.setText("ms/dia");
        getContentPane().add(duracionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        duracionValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duracionValue.setForeground(new java.awt.Color(0, 255, 51));
        duracionValue.setText("1000");
        getContentPane().add(duracionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("Analisis Financiero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        tituloDevs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDevs.setForeground(new java.awt.Color(0, 255, 51));
        tituloDevs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDevs.setText("Trabajadores");
        getContentPane().add(tituloDevs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 20));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("Analisis Operativo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/fondoSO.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doblajeNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_doblajeNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(doblajeNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(doblajeNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_doblajeNickStateChanged

    private void logicCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logicCAStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(logicCA, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(logicCA, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_logicCAStateChanged

    private void PtNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PtNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(PtNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(PtNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_PtNickStateChanged

    private void PtStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PtStarStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(PtStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(PtStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_PtStarStateChanged

    private void ensambladorNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ensambladorNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(ensambladorNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(ensambladorNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_ensambladorNickStateChanged

    private void ensambladorStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ensambladorStarStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(ensambladorStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(ensambladorStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_ensambladorStarStateChanged

    private void animacionesNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_animacionesNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(animacionesNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(animacionesNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_animacionesNickStateChanged

    private void animacionesStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_animacionesStarStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(animacionesStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(animacionesStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_animacionesStarStateChanged

    private void guionesNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(guionesNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(guionesNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_guionesNickStateChanged

    private void guionesStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesStarStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(escenariosStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(escenariosStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_guionesStarStateChanged

    private void escenariosNickStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_escenariosNickStateChanged
        if (this.click){
            if (sumar(guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick)){
                down(escenariosNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            } else {
                up(escenariosNick, guionesNick, escenariosNick, animacionesNick, doblajeNick, PtNick, ensambladorNick);
            }
            int s = (Integer)guionesNick.getValue() + (Integer)escenariosNick.getValue() + (Integer)animacionesNick.getValue() + (Integer)doblajeNick.getValue() + (Integer)PtNick.getValue() + (Integer)ensambladorNick.getValue();
            workerQtyNick.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_escenariosNickStateChanged

    private void escenariosStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_escenariosStarStateChanged
        if (this.click){
            if (sumar(guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar)){
                down(escenariosStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            } else {
                up(escenariosStar, guionesStar, escenariosStar, animacionesStar, logicCA, PtStar, ensambladorStar);
            }
            int s = (Integer)guionesStar.getValue() + (Integer)escenariosStar.getValue() + (Integer)animacionesStar.getValue() + (Integer)logicCA.getValue() + (Integer)PtStar.getValue() + (Integer)ensambladorStar.getValue();
            workerQtyStar.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_escenariosStarStateChanged

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
    
        this.subirDatos.setVisible(false);
        Nick = new Empresa("Nick", Integer.parseInt(this.duracionValue.getText()), Integer.parseInt(this.deadlineN.getText()), this.NickGuiones, this.NickEscenarios, this.NickAnimaciones, this.NickDoblajes, this.NickPT, this.NickEnsambladores, this);
        Star = new Empresa("Star", Integer.parseInt(this.duracionValue.getText()), Integer.parseInt(this.deadlineN.getText()),  this.StarGuiones, this.StarEscenarios, this.StarAnimaciones, this.StarDoblajes, this.StarPT, this.StarEnsambladores, this);

        this.guionesMaxN.setText(Integer.toString(this.Nick.estudio.maxGuiones));
        this.escenariosMaxN.setText(Integer.toString(Nick.estudio.maxEscenarios));
        this.spritesMaxN.setText(Integer.toString(Nick.estudio.maxAnimaciones));
        this.doblajesMaxN.setText(Integer.toString(Nick.estudio.maxDoblajes));
        this.DLCMaxN.setText(Integer.toString(Nick.estudio.maxPT));
    }//GEN-LAST:event_inicioBtnActionPerformed

    private void subirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirDatosActionPerformed
        this.subirDatos.setVisible(false);
        StringBuilder db = new StringBuilder();
        File file = new File(getPath());
        try {
            
            Scanner sc = new Scanner(file);
            System.out.println("flag");
            while(sc.hasNext()){
                String line = sc.nextLine();
                db.append(line);
                db.append("\n");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, 
                    "Error al leer el archivo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE); 
        }
        
        int deadline = 0;
        int dia = 0;
        
        String dbString = db.toString();
        String[] dbLines = dbString.split("\n");
        for (String dbLine : dbLines) {
            String[] dbLineList = dbLine.split(" ");
            String label = dbLineList[0];
            String value = dbLineList[1];
            if (label.contains("Deadline")){
                deadline = Integer.parseInt(value);
            }
            else {dia = Integer.parseInt(value);}

        this.deadlineN.setText(Integer.toString(deadline));
        this.duracionValue.setText(Integer.toString(dia));
            
            
        }
    }//GEN-LAST:event_subirDatosActionPerformed

    private String getPath(){
        JFileChooser selector = new JFileChooser(); 
        selector.setFileFilter(new FileNameExtensionFilter("texto", "csv"));
        selector.showOpenDialog(null); 
        File f = selector.getSelectedFile(); 
        String path = f.getAbsolutePath();
        return path;
    }
    
    public boolean sumar(javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        int qty = (Integer)spinner1.getValue()+ (Integer)spinner2.getValue() + (Integer)spinner3.getValue() + (Integer)spinner4.getValue() + (Integer)spinner5.getValue() + (Integer)spinner6.getValue();
        return qty > 12;
    }
    
    public void down(javax.swing.JSpinner aCambiar, javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        //System.out.println("Reduciendo ");
        int mayor = 0;
        javax.swing.JSpinner mayorSpinner = aCambiar;
        
        
        if (mayor < (Integer)spinner1.getValue() && (!(aCambiar==spinner1))){
            mayor = (Integer)spinner1.getValue();
            mayorSpinner = spinner1;
        }        
        if (mayor < (Integer)spinner2.getValue() && (!(aCambiar==spinner2))){
            mayor = (Integer)spinner2.getValue();
            mayorSpinner = spinner2;
        }
        if (mayor < (Integer)spinner3.getValue() && (!(aCambiar==spinner3))){
            mayor = (Integer)spinner3.getValue();
            mayorSpinner = spinner3;
        }
        if (mayor < (Integer)spinner4.getValue() && (!(aCambiar==spinner4))){
            mayor = (Integer)spinner4.getValue();
            mayorSpinner = spinner4;
        }
        if (mayor < (Integer)spinner5.getValue() && (!(aCambiar==spinner5))){
            mayor = (Integer)spinner5.getValue();
            mayorSpinner = spinner5;
        }
        if (mayor < (Integer)spinner6.getValue() && (!(aCambiar==spinner6))){
            mayor = (Integer)spinner6.getValue();
            mayorSpinner = spinner6;
        }
        
        Empresa empresa = this.Star;
        if (aCambiar.getAlignmentX()<70){
            empresa = this.Nick;
        }
        balanceoRolDevs(mayorSpinner, aCambiar, empresa);
        
        this.click = false;
        mayorSpinner.setValue(mayor-1);
        this.click = true;
        
       
    }
    
    public void up(javax.swing.JSpinner aCambiar, javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        //System.out.println("Aumentando ");
        int menor = 20;
        javax.swing.JSpinner menorSpinner = aCambiar;
        
        if (menor > (Integer)spinner1.getValue() && (!(aCambiar==spinner1))){
            menor = (Integer)spinner1.getValue();
            menorSpinner = spinner1;
        }
        if (menor > (Integer)spinner2.getValue() && (!(aCambiar==spinner2))){
            menor = (Integer)spinner2.getValue();
            menorSpinner = spinner2;
        }
        if (menor > (Integer)spinner3.getValue() && (!(aCambiar==spinner3))){
            menor = (Integer)spinner3.getValue();
            menorSpinner = spinner3;
        }
        if (menor > (Integer)spinner4.getValue() && (!(aCambiar==spinner4))){
            menor = (Integer)spinner4.getValue();
            menorSpinner = spinner4;
        }
        if (menor > (Integer)spinner5.getValue() && (!(aCambiar==spinner5))){
            menor = (Integer)spinner5.getValue();
            menorSpinner = spinner5;
        }
        if (menor > (Integer)spinner6.getValue() && (!(aCambiar==spinner6))){
            menorSpinner = spinner6;
        }
        
        this.click = false;
        menorSpinner.setValue(menor+1);
        this.click = true;
        
        Empresa empresa = this.Star;
        if (aCambiar.getAlignmentX()<70){
            empresa = this.Nick;
        }
        balanceoRolDevs(aCambiar, menorSpinner, empresa);
        
    }
    
    public void balanceoRolDevs(javax.swing.JSpinner spinnerOrigen, javax.swing.JSpinner spinnerDestino, Empresa empresa){
        
        String tipoOrigen = spinnerOrigen.getParent().getName();
        String tipoDestino = spinnerDestino.getParent().getName();
        
        System.out.println("Cambiando trabajador de " + tipoOrigen + " por uno de " + tipoDestino + " en " + empresa.name);
        
        for (Worker dev : empresa.devs) {
            if (dev.rol.equals(tipoOrigen)) {
                dev.rol = tipoDestino;
                break;
                
            }
        }
        
    }
    
    public void updateValues(){
        
        this.guionesDisponNick.setText(Integer.toString(Nick.estudio.guiones));
        this.escenariosDisponNick.setText(Integer.toString(Nick.estudio.escenarios));
        this.animacionesDisponNick.setText(Integer.toString(Nick.estudio.animaciones));
        this.doblajesDisponNick.setText(Integer.toString(Nick.estudio.doblajes));
        this.PTDisponNick.setText(Integer.toString(Nick.estudio.PT));
        
        this.guionesDisponStar.setText(Integer.toString(Star.estudio.guiones));
        this.escenariosDisponStar.setText(Integer.toString(Star.estudio.escenarios));
        this.animacionesDisponStar.setText(Integer.toString(Star.estudio.animaciones));
        this.doblajesDisponStar.setText(Integer.toString(Star.estudio.doblajes));
        this.PTDisponStar.setText(Integer.toString(Star.estudio.PT));
 
        this.qtyListosEstNick.setText(Integer.toString(Nick.estudio.capituloE));
        this.qtyListosPTNick.setText(Integer.toString(Nick.estudio.capituloPT));
        this.qtyListosEstStar.setText(Integer.toString(Star.estudio.capituloE));
        this.qtyListosPTStar.setText(Integer.toString(Star.estudio.capituloPT));
    }
    
    
    public void actualizarIngreso(long valor, String empresaNombre){
        if ("Nick".equals(empresaNombre)){
           this.ingresoNick.setText(Long.toString(valor));
        } else {
            this.ingresoStar.setText(Long.toString(valor));
        }
    }
    
    public void actualizarCostos(){
        for (Worker dev : this.Nick.devs) {
            costosNickValue += dev.wage;
        }
        for (Worker dev : this.Star.devs) {
            costosStarValue += dev.wage;
        }

        costosNickValue += 480; //salario gerente
        costosStarValue += 480;

        costosNickValue += 720; //salario director    
        costosStarValue += 720;

        this.costosStar.setText(Long.toString(costosStarValue));
        this.costosNick.setText(Long.toString(costosNickValue));
    }
    
    public void actualizarProfit(){
        long profitNintendoValue = Integer.valueOf(this.ingresoNick.getText())-Integer.valueOf(this.costosNick.getText());
        long profitCapComValue = Integer.valueOf(this.ingresoStar.getText())-Integer.valueOf(this.costosStar.getText());
        this.profitNick.setText(Long.toString(profitNintendoValue));
        this.profitStar.setText(Long.toString(profitCapComValue));
    }
    
    public void atrapado(Empresa empresa, int qtyFaltas, int montoDescontado){
        if ("Nick".equals(empresa.name)){
            this.qtyFaltasNick.setText(Integer.toString(qtyFaltas));
            this.sueldoDescontadoNick.setText(Integer.toString(montoDescontado));
        }else {
            this.qtyFaltasStar.setText(Integer.toString(qtyFaltas));
            this.sueldoDescontadoStar.setText(Integer.toString(montoDescontado));
        }
    }
    
    public void estadoPM(boolean Anime, Empresa empresa){
        if (Anime){
            if ("Nick".equals(empresa.name)){
                this.estadoPMNick.setText("viendo Anime");
            } else {
                this.estadoPMStar.setText("viendo Anime");
            } 
        }else {
            if ("Nick".equals(empresa.name)){
                this.estadoPMNick.setText("trabajando");
            } else {
                this.estadoPMStar.setText("trabajando");
            }
        }
    }
    
    public void actualizarDeadline(int n){
        this.deadlineN.setText(Integer.toString(n));
    }
    
    public void estadoDirector(boolean vigila, boolean administrativo, boolean distribuye, Empresa empresa){
        if ("Nick".equals(empresa.name)){
            if (vigila){
                this.estadoDirectorNick.setText("vigila");
            }
            if (administrativo){
                this.estadoDirectorNick.setText("administrativo");
            }
            if (distribuye){
                this.estadoDirectorNick.setText("distribuye");
            }
        } else {
            if (vigila){
                this.estadoDirectorStar.setText("vigila");
            }
            if (administrativo){
                this.estadoDirectorStar.setText("administrativo");
            }
            if (distribuye){
                this.estadoDirectorStar.setText("distribuye");
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapComPMYDirector;
    private javax.swing.JLabel DLCMaxN;
    private javax.swing.JPanel DLCPanDispon;
    private javax.swing.JPanel DLCPanel;
    private javax.swing.JLabel DirectorPMTitulo;
    private javax.swing.JLabel Doblajes;
    private javax.swing.JLabel Est;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NintendoPMYDirector;
    private javax.swing.JLabel PMTitulo;
    private javax.swing.JPanel PMyDirector;
    private javax.swing.JLabel PT;
    private javax.swing.JLabel PTDispon;
    private javax.swing.JLabel PTDisponNick;
    private javax.swing.JLabel PTDisponStar;
    private javax.swing.JLabel PTMax;
    private javax.swing.JSpinner PtNick;
    private javax.swing.JSpinner PtStar;
    private javax.swing.JLabel animacionesDisponNick;
    private javax.swing.JLabel animacionesDisponStar;
    private javax.swing.JLabel animacionesMax;
    private javax.swing.JSpinner animacionesNick;
    private javax.swing.JSpinner animacionesStar;
    private javax.swing.JLabel animadores;
    private javax.swing.JLabel animadoresDispon;
    private javax.swing.JLabel capMax;
    private javax.swing.JLabel conPT;
    private javax.swing.JLabel costosNick;
    private javax.swing.JLabel costosStar;
    private javax.swing.JLabel costosTitle;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadlineN;
    private javax.swing.JPanel deadlinePanel;
    private javax.swing.JLabel devCA;
    private javax.swing.JLabel devNI;
    private javax.swing.JLabel devQty;
    private javax.swing.JPanel devsPanel;
    private javax.swing.JPanel devsQtyPanel;
    private javax.swing.JLabel directorTitulo;
    private javax.swing.JLabel disponCA;
    private javax.swing.JLabel disponNI;
    private javax.swing.JPanel disponibilidadPanel;
    private javax.swing.JSpinner doblajeNick;
    private javax.swing.JLabel doblajesDispon;
    private javax.swing.JLabel doblajesDisponNick;
    private javax.swing.JLabel doblajesDisponStar;
    private javax.swing.JLabel doblajesMax;
    private javax.swing.JLabel doblajesMaxN;
    private javax.swing.JLabel duracionTitle;
    private javax.swing.JLabel duracionValue;
    private javax.swing.JLabel econCapCom;
    private javax.swing.JLabel econNintendo;
    private javax.swing.JPanel econPanel;
    private javax.swing.JSpinner ensambladorNick;
    private javax.swing.JSpinner ensambladorStar;
    private javax.swing.JLabel ensambladores;
    private javax.swing.JLabel escenario;
    private javax.swing.JLabel escenariosDispon;
    private javax.swing.JLabel escenariosDisponNick;
    private javax.swing.JLabel escenariosDisponStar;
    private javax.swing.JLabel escenariosMax;
    private javax.swing.JLabel escenariosMaxN;
    private javax.swing.JSpinner escenariosNick;
    private javax.swing.JSpinner escenariosStar;
    private javax.swing.JLabel estadoDirectorNick;
    private javax.swing.JLabel estadoDirectorStar;
    private javax.swing.JLabel estadoPMNick;
    private javax.swing.JLabel estadoPMStar;
    private javax.swing.JLabel faltasTitulo;
    private javax.swing.JPanel guionPanel;
    private javax.swing.JLabel guiones;
    private javax.swing.JLabel guionesDispon;
    private javax.swing.JLabel guionesDisponNick;
    private javax.swing.JLabel guionesDisponStar;
    private javax.swing.JLabel guionesMax;
    private javax.swing.JLabel guionesMaxN;
    private javax.swing.JSpinner guionesNick;
    private javax.swing.JSpinner guionesStar;
    private javax.swing.JLabel ingresoNick;
    private javax.swing.JLabel ingresoStar;
    private javax.swing.JLabel ingresos;
    private javax.swing.JButton inicioBtn;
    private javax.swing.JPanel integPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel listos;
    private javax.swing.JLabel listosTitle;
    private javax.swing.JLabel listosTitle1;
    private javax.swing.JLabel listosTitleCA;
    private javax.swing.JLabel listosTitleNI;
    private javax.swing.JSpinner logicCA;
    private javax.swing.JPanel logicPanel;
    private javax.swing.JPanel logicPanelDispon;
    private javax.swing.JPanel maxCapacidad;
    private javax.swing.JPanel narrativaPanelDispon;
    private javax.swing.JPanel nivelesPanel;
    private javax.swing.JPanel nivelesPanelDispon;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel profitNick;
    private javax.swing.JLabel profitStar;
    private javax.swing.JLabel qtyFaltasNick;
    private javax.swing.JLabel qtyFaltasStar;
    private javax.swing.JLabel qtyFaltasTitulo;
    private javax.swing.JLabel qtyListosEstNick;
    private javax.swing.JLabel qtyListosEstStar;
    private javax.swing.JLabel qtyListosPTNick;
    private javax.swing.JLabel qtyListosPTStar;
    private javax.swing.JLabel spritesMaxN;
    private javax.swing.JPanel spritesPanel;
    private javax.swing.JPanel spritesPanelDispon;
    private javax.swing.JButton subirDatos;
    private javax.swing.JLabel sueldoDescontadoNick;
    private javax.swing.JLabel sueldoDescontadoStar;
    private javax.swing.JLabel sueldoDescontadoTitulo;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel tituloDevs;
    private javax.swing.JLabel tituloDispon;
    private javax.swing.JLabel workerQtyNick;
    private javax.swing.JLabel workerQtyStar;
    // End of variables declaration//GEN-END:variables
}
