/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Company;
import Clases.Worker;


public class GUI extends javax.swing.JFrame {

    public Company Nickelodeon;
    public Company Starchannel; 
    int NIDevNarrativa; 
    int NIDevNiveles; 
    int NIDevSprites;
    int NIDevLogica;
    int NIDevDLCs;
    int NIDevIntegs; 
    int CADevNarrativa; 
    int CADevNiveles; 
    int CADevSprites;
    int CADevLogica;
    int CADevDLCs;
    int CADevIntegs;
    long costosCapComValue;
    long costosNintendoValue;
    boolean click = true;
    
    public GUI() {
        
        
        this.setResizable(false);
        initComponents();
        
        this.guionPanel.setName("guiones");
        this.nivelesPanel.setName("escenarios");
        this.spritesPanel.setName("animadores");
        this.logicPanel.setName("dobaljes");
        this.DLCPanel.setName("PlotTwists");
        this.integPanel.setName("ensambladores");
        
        
        this.NIDevNarrativa = (Integer)guionesNI.getValue();
        this.NIDevNiveles = (Integer)nivelesNI.getValue();
        this.NIDevSprites = (Integer)spritesNI.getValue();
        this.NIDevLogica = (Integer)logicNI.getValue();
        this.NIDevDLCs = (Integer)NIDLC.getValue();
        this.NIDevIntegs = (Integer)integsNI.getValue();
        
//        int qtyNI = this.NIDevNarrativa + this.NIDevNiveles + this.NIDevSprites + this.NIDevLogica + this.NIDevDLCs + this.NIDevIntegs;
//        System.out.println(qtyNI);
//        this.devQtyNI.setText(Integer.toString(qtyNI));
//        this.devQtyNI.setText(Integer.toString(qtyNI));
        
        this.CADevNarrativa = (Integer)guionesCA.getValue();
        this.CADevNiveles = (Integer)nivelesCA.getValue();
        this.CADevSprites = (Integer)spritesCA.getValue();
        this.CADevLogica = (Integer)logicCA.getValue();
        this.CADevDLCs = (Integer)CADLC.getValue();
        this.CADevIntegs = (Integer)integsCA.getValue();
        
        this.costosNintendoValue = 0;
        this.costosNintendoValue = 0;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devsPanel = new javax.swing.JPanel();
        devCA = new javax.swing.JLabel();
        devNI = new javax.swing.JLabel();
        logicPanel = new javax.swing.JPanel();
        logicLbl = new javax.swing.JLabel();
        logicNI = new javax.swing.JSpinner();
        logicCA = new javax.swing.JSpinner();
        DLCPanel = new javax.swing.JPanel();
        DLC = new javax.swing.JLabel();
        NIDLC = new javax.swing.JSpinner();
        CADLC = new javax.swing.JSpinner();
        devsQtyPanel = new javax.swing.JPanel();
        devQtyCA = new javax.swing.JLabel();
        devQty = new javax.swing.JLabel();
        devQtyNI = new javax.swing.JLabel();
        integPanel = new javax.swing.JPanel();
        integs = new javax.swing.JLabel();
        integsNI = new javax.swing.JSpinner();
        integsCA = new javax.swing.JSpinner();
        spritesPanel = new javax.swing.JPanel();
        sprites = new javax.swing.JLabel();
        spritesNI = new javax.swing.JSpinner();
        spritesCA = new javax.swing.JSpinner();
        guionPanel = new javax.swing.JPanel();
        guiones = new javax.swing.JLabel();
        guionesNI = new javax.swing.JSpinner();
        guionesCA = new javax.swing.JSpinner();
        nivelesPanel = new javax.swing.JPanel();
        niveles = new javax.swing.JLabel();
        nivelesNI = new javax.swing.JSpinner();
        nivelesCA = new javax.swing.JSpinner();
        tituloDevs = new javax.swing.JLabel();
        disponibilidadPanel = new javax.swing.JPanel();
        tituloDispon = new javax.swing.JLabel();
        disponCA = new javax.swing.JLabel();
        disponNI = new javax.swing.JLabel();
        DLCPanDispon = new javax.swing.JPanel();
        DLCDispon = new javax.swing.JLabel();
        DLCDisponNI = new javax.swing.JLabel();
        DLCDisponCA = new javax.swing.JLabel();
        nivelesPanelDispon = new javax.swing.JPanel();
        nivelesDispon = new javax.swing.JLabel();
        nivelesDisponNI = new javax.swing.JLabel();
        nivelesDisponCA = new javax.swing.JLabel();
        logicPanelDispon = new javax.swing.JPanel();
        sistemasDispon = new javax.swing.JLabel();
        logicDisponNI = new javax.swing.JLabel();
        logicDisponCA = new javax.swing.JLabel();
        narrativaPanelDispon = new javax.swing.JPanel();
        guionesDispon = new javax.swing.JLabel();
        guionesDisponNI = new javax.swing.JLabel();
        guionesDisponCA = new javax.swing.JLabel();
        spritesPanelDispon = new javax.swing.JPanel();
        spritesDispon = new javax.swing.JLabel();
        spritesDisponNI = new javax.swing.JLabel();
        spritesDisponCA = new javax.swing.JLabel();
        maxCapacidad = new javax.swing.JPanel();
        capMax = new javax.swing.JLabel();
        guionesMax = new javax.swing.JLabel();
        nivelesMax = new javax.swing.JLabel();
        spritesMax = new javax.swing.JLabel();
        sistemasMax = new javax.swing.JLabel();
        DLCMax = new javax.swing.JLabel();
        spritesMaxN = new javax.swing.JLabel();
        guionesMaxN = new javax.swing.JLabel();
        nivelesMaxN = new javax.swing.JLabel();
        DLCMaxN = new javax.swing.JLabel();
        sistemasMaxN = new javax.swing.JLabel();
        listos = new javax.swing.JPanel();
        listosTitle = new javax.swing.JLabel();
        listosTitleCA = new javax.swing.JLabel();
        listosTitleNI = new javax.swing.JLabel();
        conDLC = new javax.swing.JLabel();
        qtyListosDLCNI = new javax.swing.JLabel();
        qtyListosDLCCA = new javax.swing.JLabel();
        Est = new javax.swing.JLabel();
        qtyListosEstNI = new javax.swing.JLabel();
        qtyListosEstCA = new javax.swing.JLabel();
        deadlinePanel = new javax.swing.JPanel();
        deadline = new javax.swing.JLabel();
        deadlineN = new javax.swing.JLabel();
        iniciarBtn = new javax.swing.JToggleButton();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        econPanel = new javax.swing.JPanel();
        listosTitle1 = new javax.swing.JLabel();
        econCapCom = new javax.swing.JLabel();
        econNintendo = new javax.swing.JLabel();
        ingresoNintendo = new javax.swing.JLabel();
        costosNintendo = new javax.swing.JLabel();
        profitNintendo = new javax.swing.JLabel();
        ingresoCapCom = new javax.swing.JLabel();
        costosCapCom = new javax.swing.JLabel();
        profitCapCom = new javax.swing.JLabel();
        costosTitle = new javax.swing.JLabel();
        ingresos = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devsPanel.setOpaque(false);
        devsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devCA.setForeground(new java.awt.Color(255, 255, 255));
        devCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devCA.setText("CapCom");
        devsPanel.add(devCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 20, 60, 20));

        devNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devNI.setForeground(new java.awt.Color(255, 255, 255));
        devNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devNI.setText("Nintendo");
        devsPanel.add(devNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 20));

        logicPanel.setOpaque(false);
        logicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logicLbl.setForeground(new java.awt.Color(255, 255, 255));
        logicLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicLbl.setText("Sistemas");
        logicPanel.add(logicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        logicNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        logicNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        logicNI.setToolTipText("");
        logicNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logicNIStateChanged(evt);
            }
        });
        logicPanel.add(logicNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        logicCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        logicCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        logicCA.setToolTipText("");
        logicCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logicCAStateChanged(evt);
            }
        });
        logicPanel.add(logicCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(logicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        DLCPanel.setOpaque(false);
        DLCPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DLC.setForeground(new java.awt.Color(255, 255, 255));
        DLC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLC.setText("DLC");
        DLCPanel.add(DLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        NIDLC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        NIDLC.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        NIDLC.setToolTipText("");
        NIDLC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NIDLCStateChanged(evt);
            }
        });
        DLCPanel.add(NIDLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        CADLC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CADLC.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        CADLC.setToolTipText("");
        CADLC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CADLCStateChanged(evt);
            }
        });
        DLCPanel.add(CADLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(DLCPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        devsQtyPanel.setOpaque(false);
        devsQtyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devQtyCA.setForeground(new java.awt.Color(255, 255, 255));
        devQtyCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQtyCA.setText("12");
        devsQtyPanel.add(devQtyCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        devQty.setForeground(new java.awt.Color(255, 255, 255));
        devQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQty.setText("Devs");
        devsQtyPanel.add(devQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 20));

        devQtyNI.setForeground(new java.awt.Color(255, 255, 255));
        devQtyNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQtyNI.setText("12");
        devsQtyPanel.add(devQtyNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        devsPanel.add(devsQtyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        integPanel.setOpaque(false);
        integPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        integs.setForeground(new java.awt.Color(255, 255, 255));
        integs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integs.setText("Integradores");
        integPanel.add(integs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        integsNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        integsNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        integsNI.setToolTipText("");
        integsNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                integsNIStateChanged(evt);
            }
        });
        integPanel.add(integsNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        integsCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        integsCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        integsCA.setToolTipText("");
        integsCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                integsCAStateChanged(evt);
            }
        });
        integPanel.add(integsCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(integPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        spritesPanel.setOpaque(false);
        spritesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sprites.setForeground(new java.awt.Color(255, 255, 255));
        sprites.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sprites.setText("Sprites");
        spritesPanel.add(sprites, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        spritesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spritesNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        spritesNI.setToolTipText("");
        spritesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spritesNIStateChanged(evt);
            }
        });
        spritesPanel.add(spritesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        spritesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spritesCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        spritesCA.setToolTipText("");
        spritesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spritesCAStateChanged(evt);
            }
        });
        spritesPanel.add(spritesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(spritesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        guionPanel.setOpaque(false);
        guionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiones.setForeground(new java.awt.Color(255, 255, 255));
        guiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guiones.setText("Guiones");
        guionPanel.add(guiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        guionesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        guionesNI.setToolTipText("");
        guionesNI.setRequestFocusEnabled(false);
        guionesNI.setValue(2);
        guionesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesNIStateChanged(evt);
            }
        });
        guionPanel.add(guionesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        guionesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        guionesCA.setToolTipText("");
        guionesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesCAStateChanged(evt);
            }
        });
        guionPanel.add(guionesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(guionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        nivelesPanel.setOpaque(false);
        nivelesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        niveles.setForeground(new java.awt.Color(255, 255, 255));
        niveles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        niveles.setText("Niveles");
        nivelesPanel.add(niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        nivelesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nivelesNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        nivelesNI.setToolTipText("");
        nivelesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nivelesNIStateChanged(evt);
            }
        });
        nivelesPanel.add(nivelesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        nivelesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nivelesCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        nivelesCA.setToolTipText("");
        nivelesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nivelesCAStateChanged(evt);
            }
        });
        nivelesPanel.add(nivelesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        devsPanel.add(nivelesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        tituloDevs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDevs.setForeground(new java.awt.Color(255, 255, 255));
        tituloDevs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDevs.setText("DEVELOPERS");
        devsPanel.add(tituloDevs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 20));

        getContentPane().add(devsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 250));

        disponibilidadPanel.setOpaque(false);
        disponibilidadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloDispon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDispon.setForeground(new java.awt.Color(255, 255, 255));
        tituloDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDispon.setText("DISPONIBILIDAD");
        disponibilidadPanel.add(tituloDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 20));

        disponCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponCA.setForeground(new java.awt.Color(255, 255, 255));
        disponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponCA.setText("CapCom");
        disponibilidadPanel.add(disponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 20));

        disponNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponNI.setForeground(new java.awt.Color(255, 255, 255));
        disponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponNI.setText("Nintendo");
        disponibilidadPanel.add(disponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 20));

        DLCPanDispon.setOpaque(false);
        DLCPanDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DLCDispon.setForeground(new java.awt.Color(255, 255, 255));
        DLCDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDispon.setText("DLC");
        DLCPanDispon.add(DLCDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        DLCDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        DLCDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDisponNI.setText("0");
        DLCPanDispon.add(DLCDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        DLCDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        DLCDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDisponCA.setText("0");
        DLCPanDispon.add(DLCDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(DLCPanDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        nivelesPanelDispon.setOpaque(false);
        nivelesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nivelesDispon.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDispon.setText("Niveles");
        nivelesPanelDispon.add(nivelesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        nivelesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDisponNI.setText("0");
        nivelesPanelDispon.add(nivelesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        nivelesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDisponCA.setText("0");
        nivelesPanelDispon.add(nivelesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(nivelesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        logicPanelDispon.setOpaque(false);
        logicPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sistemasDispon.setForeground(new java.awt.Color(255, 255, 255));
        sistemasDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistemasDispon.setText("Sistemas");
        logicPanelDispon.add(sistemasDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        logicDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        logicDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicDisponNI.setText("0");
        logicPanelDispon.add(logicDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        logicDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        logicDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicDisponCA.setText("0");
        logicPanelDispon.add(logicDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(logicPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        narrativaPanelDispon.setOpaque(false);
        narrativaPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guionesDispon.setForeground(new java.awt.Color(255, 255, 255));
        guionesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDispon.setText("Guiones");
        narrativaPanelDispon.add(guionesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        guionesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponNI.setText("0");
        narrativaPanelDispon.add(guionesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        guionesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponCA.setText("0");
        narrativaPanelDispon.add(guionesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(narrativaPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        spritesPanelDispon.setOpaque(false);
        spritesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spritesDispon.setForeground(new java.awt.Color(255, 255, 255));
        spritesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDispon.setText("Sprite Sets");
        spritesPanelDispon.add(spritesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        spritesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        spritesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDisponNI.setText("0");
        spritesPanelDispon.add(spritesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        spritesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        spritesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDisponCA.setText("0");
        spritesPanelDispon.add(spritesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(spritesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        getContentPane().add(disponibilidadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, 220));

        maxCapacidad.setOpaque(false);
        maxCapacidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        capMax.setForeground(new java.awt.Color(255, 255, 255));
        capMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capMax.setText("CAPACIDAD MÁXIMA");
        maxCapacidad.add(capMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        guionesMax.setForeground(new java.awt.Color(255, 255, 255));
        guionesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guionesMax.setText("Guiones");
        maxCapacidad.add(guionesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        nivelesMax.setForeground(new java.awt.Color(255, 255, 255));
        nivelesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nivelesMax.setText("Niveles");
        maxCapacidad.add(nivelesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 20));

        spritesMax.setForeground(new java.awt.Color(255, 255, 255));
        spritesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spritesMax.setText("Sets de Sprites");
        maxCapacidad.add(spritesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        sistemasMax.setForeground(new java.awt.Color(255, 255, 255));
        sistemasMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sistemasMax.setText("Sistemas");
        maxCapacidad.add(sistemasMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 20));

        DLCMax.setForeground(new java.awt.Color(255, 255, 255));
        DLCMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DLCMax.setText("DLCs");
        maxCapacidad.add(DLCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 20));

        spritesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        spritesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesMaxN.setText("0");
        maxCapacidad.add(spritesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        guionesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        guionesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesMaxN.setText("0");
        maxCapacidad.add(guionesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 30, 20));

        nivelesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        nivelesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesMaxN.setText("0");
        maxCapacidad.add(nivelesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 20));

        DLCMaxN.setForeground(new java.awt.Color(255, 255, 255));
        DLCMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCMaxN.setText("0");
        maxCapacidad.add(DLCMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 20));

        sistemasMaxN.setForeground(new java.awt.Color(255, 255, 255));
        sistemasMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistemasMaxN.setText("0");
        maxCapacidad.add(sistemasMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, 20));

        getContentPane().add(maxCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 130, 130));

        listos.setOpaque(false);
        listos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listosTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitle.setForeground(new java.awt.Color(255, 255, 255));
        listosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitle.setText("VIDEOJUEGOS LISTOS");
        listos.add(listosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 20));

        listosTitleCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleCA.setForeground(new java.awt.Color(255, 255, 255));
        listosTitleCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleCA.setText("CapCom");
        listos.add(listosTitleCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 20));

        listosTitleNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleNI.setForeground(new java.awt.Color(255, 255, 255));
        listosTitleNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleNI.setText("Nintendo");
        listos.add(listosTitleNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 20));

        conDLC.setForeground(new java.awt.Color(255, 255, 255));
        conDLC.setText("Con DLC");
        listos.add(conDLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        qtyListosDLCNI.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosDLCNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosDLCNI.setText("0");
        listos.add(qtyListosDLCNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, -1));

        qtyListosDLCCA.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosDLCCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosDLCCA.setText("0");
        listos.add(qtyListosDLCCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 30, -1));

        Est.setForeground(new java.awt.Color(255, 255, 255));
        Est.setText("Estándar");
        listos.add(Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        qtyListosEstNI.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstNI.setText("0");
        listos.add(qtyListosEstNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        qtyListosEstCA.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstCA.setText("0");
        listos.add(qtyListosEstCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, -1));

        getContentPane().add(listos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        deadlinePanel.setOpaque(false);
        deadlinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deadline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deadline.setForeground(new java.awt.Color(255, 255, 255));
        deadline.setText("Deadline");
        deadlinePanel.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        deadlineN.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        deadlineN.setForeground(new java.awt.Color(255, 255, 255));
        deadlineN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadlineN.setText("30");
        deadlinePanel.add(deadlineN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, -1));

        getContentPane().add(deadlinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 140, 70));

        iniciarBtn.setBackground(new java.awt.Color(255, 102, 51));
        iniciarBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        iniciarBtn.setText("INICIAR");
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 204, 51));
        title.setText("Venezuela");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 40));

        title1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 204, 51));
        title1.setText("Desarrollo de");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 50));

        title2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 204, 51));
        title2.setText("Videojuegos en");
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 80));

        econPanel.setOpaque(false);
        econPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listosTitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitle1.setForeground(new java.awt.Color(255, 255, 255));
        listosTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitle1.setText("ASPECTO ECONÓMICO");
        econPanel.add(listosTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 20));

        econCapCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        econCapCom.setForeground(new java.awt.Color(255, 255, 255));
        econCapCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        econCapCom.setText("CapCom");
        econPanel.add(econCapCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, 20));

        econNintendo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        econNintendo.setForeground(new java.awt.Color(255, 255, 255));
        econNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        econNintendo.setText("Nintendo");
        econPanel.add(econNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        ingresoNintendo.setForeground(new java.awt.Color(255, 255, 255));
        ingresoNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoNintendo.setText("0");
        econPanel.add(ingresoNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, -1));

        costosNintendo.setForeground(new java.awt.Color(255, 255, 255));
        costosNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosNintendo.setText("0");
        econPanel.add(costosNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 110, -1));

        profitNintendo.setForeground(new java.awt.Color(255, 255, 255));
        profitNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profitNintendo.setText("0");
        econPanel.add(profitNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        ingresoCapCom.setForeground(new java.awt.Color(255, 255, 255));
        ingresoCapCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoCapCom.setText("0");
        econPanel.add(ingresoCapCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        costosCapCom.setForeground(new java.awt.Color(255, 255, 255));
        costosCapCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosCapCom.setText("0");
        econPanel.add(costosCapCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));

        profitCapCom.setForeground(new java.awt.Color(255, 255, 255));
        profitCapCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profitCapCom.setText("0");
        econPanel.add(profitCapCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, -1));

        costosTitle.setForeground(new java.awt.Color(255, 255, 255));
        costosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costosTitle.setText("Costos");
        econPanel.add(costosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, -1));

        ingresos.setForeground(new java.awt.Color(255, 255, 255));
        ingresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresos.setText("Ingresos");
        econPanel.add(ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 270, -1));

        profit.setForeground(new java.awt.Color(255, 255, 255));
        profit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profit.setText("Utilidad");
        econPanel.add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, -1));

        getContentPane().add(econPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 270, 120));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logicNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logicNIStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(logicNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(logicNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_logicNIStateChanged

    private void logicCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logicCAStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(logicCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(logicCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_logicCAStateChanged

    private void NIDLCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NIDLCStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(NIDLC, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(NIDLC, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_NIDLCStateChanged

    private void CADLCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CADLCStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(CADLC, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(CADLC, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_CADLCStateChanged

    private void integsNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_integsNIStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(integsNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(integsNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_integsNIStateChanged

    private void integsCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_integsCAStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(integsCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(integsCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_integsCAStateChanged

    private void spritesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spritesNIStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(spritesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(spritesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_spritesNIStateChanged

    private void spritesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spritesCAStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(spritesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(spritesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_spritesCAStateChanged

    private void guionesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesNIStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(guionesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(guionesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_guionesNIStateChanged

    private void guionesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesCAStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(nivelesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(nivelesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_guionesCAStateChanged

    private void nivelesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nivelesNIStateChanged
        if (this.click){
            if (sumar(guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI)){
                down(nivelesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            } else {
                up(nivelesNI, guionesNI, nivelesNI, spritesNI, logicNI, NIDLC, integsNI);
            }
            int s = (Integer)guionesNI.getValue() + (Integer)nivelesNI.getValue() + (Integer)spritesNI.getValue() + (Integer)logicNI.getValue() + (Integer)NIDLC.getValue() + (Integer)integsNI.getValue();
            devQtyNI.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_nivelesNIStateChanged

    private void nivelesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nivelesCAStateChanged
        if (this.click){
            if (sumar(guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA)){
                down(nivelesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            } else {
                up(nivelesCA, guionesCA, nivelesCA, spritesCA, logicCA, CADLC, integsCA);
            }
            int s = (Integer)guionesCA.getValue() + (Integer)nivelesCA.getValue() + (Integer)spritesCA.getValue() + (Integer)logicCA.getValue() + (Integer)CADLC.getValue() + (Integer)integsCA.getValue();
            devQtyCA.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_nivelesCAStateChanged

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        
        Nickelodeon = new Company("Nickelodeon", 500, 30, this.NIDevNarrativa, this.NIDevNiveles, this.NIDevSprites, this.NIDevLogica, this.NIDevDLCs, this.NIDevIntegs, this);
        Starchannel = new Company("Star Channel", 50, 30,  this.CADevNarrativa, this.CADevNiveles, this.CADevSprites, this.CADevLogica, this.CADevDLCs, this.CADevIntegs, this);
        
        this.guionesMaxN.setText(Integer.toString(Nickelodeon.estudio.maxGuiones));
        this.nivelesMaxN.setText(Integer.toString(Nickelodeon.estudio.maxEscenarios));
        this.spritesMaxN.setText(Integer.toString(Nickelodeon.estudio.maxAnimadores));
        this.sistemasMaxN.setText(Integer.toString(Nickelodeon.estudio.maxDoblajes));
        this.DLCMaxN.setText(Integer.toString(Nickelodeon.estudio.maxPT));
    }//GEN-LAST:event_iniciarBtnActionPerformed

    public boolean sumar(javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        int qty = (Integer)spinner1.getValue()+ (Integer)spinner2.getValue() + (Integer)spinner3.getValue() + (Integer)spinner4.getValue() + (Integer)spinner5.getValue() + (Integer)spinner6.getValue();
        return qty > 12;
    }
    
    public void down(javax.swing.JSpinner aCambiar, javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        //System.out.println("Reduciendo ");
        int mayor = 0;
        javax.swing.JSpinner mayorSpinner = aCambiar;
        
        
        if (mayor < (Integer)spinner1.getValue() && (!(aCambiar==spinner1))){
            mayor = (Integer)spinner1.getValue();
            mayorSpinner = spinner1;
        }        
        if (mayor < (Integer)spinner2.getValue() && (!(aCambiar==spinner2))){
            mayor = (Integer)spinner2.getValue();
            mayorSpinner = spinner2;
        }
        if (mayor < (Integer)spinner3.getValue() && (!(aCambiar==spinner3))){
            mayor = (Integer)spinner3.getValue();
            mayorSpinner = spinner3;
        }
        if (mayor < (Integer)spinner4.getValue() && (!(aCambiar==spinner4))){
            mayor = (Integer)spinner4.getValue();
            mayorSpinner = spinner4;
        }
        if (mayor < (Integer)spinner5.getValue() && (!(aCambiar==spinner5))){
            mayor = (Integer)spinner5.getValue();
            mayorSpinner = spinner5;
        }
        if (mayor < (Integer)spinner6.getValue() && (!(aCambiar==spinner6))){
            mayor = (Integer)spinner6.getValue();
            mayorSpinner = spinner6;
        }
        
        Company empresa = this.Starchannel;
        if (aCambiar.getAlignmentX()<70){
            empresa = this.Nickelodeon;
        }
        balanceoRolDevs(mayorSpinner, aCambiar, empresa);
        
        this.click = false;
        mayorSpinner.setValue(mayor-1);
        this.click = true;
        
       
    }
    
    public void up(javax.swing.JSpinner aCambiar, javax.swing.JSpinner spinner1, javax.swing.JSpinner spinner2, javax.swing.JSpinner spinner3, javax.swing.JSpinner spinner4, javax.swing.JSpinner spinner5, javax.swing.JSpinner spinner6){
        //System.out.println("Aumentando ");
        int menor = 20;
        javax.swing.JSpinner menorSpinner = aCambiar;
        
        if (menor > (Integer)spinner1.getValue() && (!(aCambiar==spinner1))){
            menor = (Integer)spinner1.getValue();
            menorSpinner = spinner1;
        }
        if (menor > (Integer)spinner2.getValue() && (!(aCambiar==spinner2))){
            menor = (Integer)spinner2.getValue();
            menorSpinner = spinner2;
        }
        if (menor > (Integer)spinner3.getValue() && (!(aCambiar==spinner3))){
            menor = (Integer)spinner3.getValue();
            menorSpinner = spinner3;
        }
        if (menor > (Integer)spinner4.getValue() && (!(aCambiar==spinner4))){
            menor = (Integer)spinner4.getValue();
            menorSpinner = spinner4;
        }
        if (menor > (Integer)spinner5.getValue() && (!(aCambiar==spinner5))){
            menor = (Integer)spinner5.getValue();
            menorSpinner = spinner5;
        }
        if (menor > (Integer)spinner6.getValue() && (!(aCambiar==spinner6))){
            menorSpinner = spinner6;
        }
        
        this.click = false;
        menorSpinner.setValue(menor+1);
        this.click = true;
        
        Company empresa = this.Starchannel;
        if (aCambiar.getAlignmentX()<70){
            empresa = this.Nickelodeon;
        }
        balanceoRolDevs(aCambiar, menorSpinner, empresa);
        
    }
    
    public void balanceoRolDevs(javax.swing.JSpinner spinnerOrigen, javax.swing.JSpinner spinnerDestino, Company empresa){
        
        String tipoOrigen = spinnerOrigen.getParent().getName();
        String tipoDestino = spinnerDestino.getParent().getName();
        
        System.out.println("Cambiando trabajador de " + tipoOrigen + " por uno de " + tipoDestino + " en " + empresa.name);
        
        for (Worker dev : empresa.workers) {
            if (dev.rol.equals(tipoOrigen)) {
                dev.rol = tipoDestino;
                break;
                
            }
        }
        
    }
    
    public void updateValues(){
        
        this.guionesDisponNI.setText(Integer.toString(Nickelodeon.estudio.guiones));
        this.nivelesDisponNI.setText(Integer.toString(Nickelodeon.estudio.escenarios));
        this.spritesDisponNI.setText(Integer.toString(Nickelodeon.estudio.animadores));
        this.logicDisponNI.setText(Integer.toString(Nickelodeon.estudio.doblajes));
        this.DLCDisponNI.setText(Integer.toString(Nickelodeon.estudio.plotTwists));
        
        this.guionesDisponCA.setText(Integer.toString(Starchannel.estudio.guiones));
        this.nivelesDisponCA.setText(Integer.toString(Starchannel.estudio.escenarios));
        this.spritesDisponCA.setText(Integer.toString(Starchannel.estudio.animadores));
        this.logicDisponCA.setText(Integer.toString(Starchannel.estudio.doblajes));
        this.DLCDisponCA.setText(Integer.toString(Starchannel.estudio.plotTwists));
 
        this.qtyListosEstNI.setText(Integer.toString(Nickelodeon.estudio.normalEpisodes));
        this.qtyListosDLCNI.setText(Integer.toString(Nickelodeon.estudio.PTepisode));
        this.qtyListosEstCA.setText(Integer.toString(Starchannel.estudio.normalEpisodes));
        this.qtyListosDLCCA.setText(Integer.toString(Starchannel.estudio.PTepisode));
    }
    
    
    public void actualizarIngreso(long valor, String empresaNombre){
        if ("Nintendo".equals(empresaNombre)){
           this.ingresoNintendo.setText(Long.toString(valor));
        } else {
            this.ingresoCapCom.setText(Long.toString(valor));
        }
    }
    
    public void actualizarCostos(){
        for (Worker dev : this.Nickelodeon.workers) {
            costosNintendoValue += dev.wage;
        }
        for (Worker dev : this.Starchannel.workers) {
            costosCapComValue += dev.wage;
        }

        costosNintendoValue += 480; //salario gerente
        costosCapComValue += 480;

        costosNintendoValue += 720; //salario director    
        costosCapComValue += 720;

        this.costosCapCom.setText(Long.toString(costosCapComValue));
        this.costosNintendo.setText(Long.toString(costosNintendoValue));
    }
    
    public void actualizarProfit(){
        long profitNintendoValue = Integer.valueOf(this.ingresoNintendo.getText())-Integer.valueOf(this.costosNintendo.getText());
        long profitCapComValue = Integer.valueOf(this.ingresoCapCom.getText())-Integer.valueOf(this.costosCapCom.getText());
        this.profitNintendo.setText(Long.toString(profitNintendoValue));
        this.profitNintendo.setText(Long.toString(profitCapComValue));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CADLC;
    private javax.swing.JLabel DLC;
    private javax.swing.JLabel DLCDispon;
    private javax.swing.JLabel DLCDisponCA;
    private javax.swing.JLabel DLCDisponNI;
    private javax.swing.JLabel DLCMax;
    private javax.swing.JLabel DLCMaxN;
    private javax.swing.JPanel DLCPanDispon;
    private javax.swing.JPanel DLCPanel;
    private javax.swing.JLabel Est;
    private javax.swing.JLabel Fondo;
    private javax.swing.JSpinner NIDLC;
    private javax.swing.JLabel capMax;
    private javax.swing.JLabel conDLC;
    private javax.swing.JLabel costosCapCom;
    private javax.swing.JLabel costosNintendo;
    private javax.swing.JLabel costosTitle;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadlineN;
    private javax.swing.JPanel deadlinePanel;
    private javax.swing.JLabel devCA;
    private javax.swing.JLabel devNI;
    private javax.swing.JLabel devQty;
    private javax.swing.JLabel devQtyCA;
    private javax.swing.JLabel devQtyNI;
    private javax.swing.JPanel devsPanel;
    private javax.swing.JPanel devsQtyPanel;
    private javax.swing.JLabel disponCA;
    private javax.swing.JLabel disponNI;
    private javax.swing.JPanel disponibilidadPanel;
    private javax.swing.JLabel econCapCom;
    private javax.swing.JLabel econNintendo;
    private javax.swing.JPanel econPanel;
    private javax.swing.JPanel guionPanel;
    private javax.swing.JLabel guiones;
    private javax.swing.JSpinner guionesCA;
    private javax.swing.JLabel guionesDispon;
    private javax.swing.JLabel guionesDisponCA;
    private javax.swing.JLabel guionesDisponNI;
    private javax.swing.JLabel guionesMax;
    private javax.swing.JLabel guionesMaxN;
    private javax.swing.JSpinner guionesNI;
    private javax.swing.JLabel ingresoCapCom;
    private javax.swing.JLabel ingresoNintendo;
    private javax.swing.JLabel ingresos;
    private javax.swing.JToggleButton iniciarBtn;
    private javax.swing.JPanel integPanel;
    private javax.swing.JLabel integs;
    private javax.swing.JSpinner integsCA;
    private javax.swing.JSpinner integsNI;
    private javax.swing.JPanel listos;
    private javax.swing.JLabel listosTitle;
    private javax.swing.JLabel listosTitle1;
    private javax.swing.JLabel listosTitleCA;
    private javax.swing.JLabel listosTitleNI;
    private javax.swing.JSpinner logicCA;
    private javax.swing.JLabel logicDisponCA;
    private javax.swing.JLabel logicDisponNI;
    private javax.swing.JLabel logicLbl;
    private javax.swing.JSpinner logicNI;
    private javax.swing.JPanel logicPanel;
    private javax.swing.JPanel logicPanelDispon;
    private javax.swing.JPanel maxCapacidad;
    private javax.swing.JPanel narrativaPanelDispon;
    private javax.swing.JLabel niveles;
    private javax.swing.JSpinner nivelesCA;
    private javax.swing.JLabel nivelesDispon;
    private javax.swing.JLabel nivelesDisponCA;
    private javax.swing.JLabel nivelesDisponNI;
    private javax.swing.JLabel nivelesMax;
    private javax.swing.JLabel nivelesMaxN;
    private javax.swing.JSpinner nivelesNI;
    private javax.swing.JPanel nivelesPanel;
    private javax.swing.JPanel nivelesPanelDispon;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel profitCapCom;
    private javax.swing.JLabel profitNintendo;
    private javax.swing.JLabel qtyListosDLCCA;
    private javax.swing.JLabel qtyListosDLCNI;
    private javax.swing.JLabel qtyListosEstCA;
    private javax.swing.JLabel qtyListosEstNI;
    private javax.swing.JLabel sistemasDispon;
    private javax.swing.JLabel sistemasMax;
    private javax.swing.JLabel sistemasMaxN;
    private javax.swing.JLabel sprites;
    private javax.swing.JSpinner spritesCA;
    private javax.swing.JLabel spritesDispon;
    private javax.swing.JLabel spritesDisponCA;
    private javax.swing.JLabel spritesDisponNI;
    private javax.swing.JLabel spritesMax;
    private javax.swing.JLabel spritesMaxN;
    private javax.swing.JSpinner spritesNI;
    private javax.swing.JPanel spritesPanel;
    private javax.swing.JPanel spritesPanelDispon;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel tituloDevs;
    private javax.swing.JLabel tituloDispon;
    // End of variables declaration//GEN-END:variables
}
